// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtxNv2kKkm7H076vBYoE_sgf54Aoz3x-I',
    appId: '1:83937718960:android:d06a22c43cc5e09b4ec175',
    messagingSenderId: '83937718960',
    projectId: 'abhinavmis-f82d0',
    storageBucket: 'abhinavmis-f82d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5rE5i3U8AK1oyqh7FLEEGTLsz0bNt5Jw',
    appId: '1:83937718960:ios:b1c33821512c9b044ec175',
    messagingSenderId: '83937718960',
    projectId: 'abhinavmis-f82d0',
    storageBucket: 'abhinavmis-f82d0.appspot.com',
    androidClientId: '83937718960-98kn6uf05ic1fvertp3n8a371r06fna4.apps.googleusercontent.com',
    iosClientId: '83937718960-ncvcm7ujuhhcjt9tmrumb7ce2af21q06.apps.googleusercontent.com',
    iosBundleId: 'com.example.inappFirebase',
  );
}
